friends = ["John", "Max", "Han", "Khan"]
print(friends)
print(friends[0])
print(friends[1])
print(friends[2])
print(friends[3])
print(friends[-1])
print(friends[-2])
print(friends[-3])
print(friends[-4])
print(friends[2:])
print(friends[1:4])
friends[2] = "Mike"
print(friends)
friends.append("Tom")
print(friends)
friends.insert(2, "Joe")
friends.remove("Mike")
print(friends)
friends.insert(3, "Olsen")
print(friends)
friends.pop()
print(friends)
friends.sort()
print(friends)
lucky_numbers = [4, 8, 15, 45, 36, 54, 9]
lucky_numbers.sort()
print(lucky_numbers)
lucky_numbers.reverse()
print(lucky_numbers)
friends.extend(lucky_numbers)
print(friends)
print(friends.index("Olsen"))
friends.clear()
print(friends)
numbers2 = lucky_numbers.copy()
print(numbers2)
